# HLint configuration for haskell-linter project
# See: https://github.com/ndmitchell/hlint

# Ignore specific suggestions where we have our own linting rules
- ignore: {name: "Use camelCase"}

# Enforce good practices
- warn: {name: "Use foldl'"}
- warn: {name: "Avoid lambda"}
- warn: {name: "Use const"}
- warn: {name: "Redundant do"}
- warn: {name: "Use when"}
- warn: {name: "Use unless"}
- warn: {name: "Use void"}
- warn: {name: "Use concatMap"}
- warn: {name: "Use mapMaybe"}
- warn: {name: "Use catMaybes"}
- warn: {name: "Use fromMaybe"}
- warn: {name: "Use maybe"}
- warn: {name: "Use isJust"}
- warn: {name: "Use isNothing"}

# Error on dangerous/partial functions
- error: {name: "Avoid fromJust"}
- error: {name: "Avoid head"}
- error: {name: "Avoid tail"}
- error: {name: "Avoid init"}
- error: {name: "Avoid last"}
- error: {name: "Avoid (!!)"}
- error: {name: "Avoid read"}
- error: {name: "Avoid error"}

# Ignore redundant constraints warning for type classes
- ignore:
    name: "Redundant constraint"
    within:
      - Linter.Types

# Allow head/tail in Utils module (we define safe alternatives)
- ignore:
    name: "Avoid head"
    within:
      - Linter.Utils
- ignore:
    name: "Avoid tail"
    within:
      - Linter.Utils
- ignore:
    name: "Avoid last"
    within:
      - Linter.Utils
- ignore:
    name: "Avoid init"
    within:
      - Linter.Utils

# Custom hints for this project
- hint:
    lhs: "head xs"
    rhs: "Linter.Utils.headMay xs"
    note: "Use safe headMay from Utils"

- hint:
    lhs: "tail xs"
    rhs: "Linter.Utils.tailMay xs"
    note: "Use safe tailMay from Utils"

- hint:
    lhs: "last xs"
    rhs: "Linter.Utils.lastMay xs"
    note: "Use safe lastMay from Utils"

# Module restrictions
- modules:
  - {name: [Data.List], within: [Linter.Utils], message: "Use Linter.Utils for safe list operations"}

# Extension recommendations
- extensions:
  - default: true
  - {name: OverloadedStrings, within: []}
  - {name: RecordWildCards, within: []}
  - {name: ImportQualifiedPost, within: []}
