---
name: code-conventions
version: "0.0.0"

dependencies:
  - base >= 4.7 && < 5
  - ghc-syntax-highlighter
  - directory
  - filepath
  - text
  - classy-prelude
  - haskell-src-exts
  - string-interpolate
  - yaml
  - hashmap
  - containers
  - vector
  - aeson
  - unordered-containers
  - bytestring
  - pretty-simple
  - split
  - record-hasfield
  - record-dot-preprocessor
  - optparse-applicative

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - DerivingVia
  - DeriveFunctor
  - DeriveGeneric
  - DeriveDataTypeable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - UndecidableInstances

library:
  source-dirs: src

executables:
  code-conventions:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -optP-Wno-nonportable-include-path
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - code-conventions

tests:
  code-conventions-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - code-conventions
      - hspec
      - text
      - bytestring
