---
name: linter
version: "0.0.0"

dependencies:
  - base >= 4.7 && < 5
  - ghc-syntax-highlighter
  - directory
  - filepath
  - text
  - classy-prelude
  - haskell-src-exts
  - string-interpolate
  - yaml
  - hashmap
  - containers
  - vector
  - aeson
  - unordered-containers
  - bytestring
  - pretty-simple
  - split

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - DerivingVia
  - DeriveFunctor
  - DeriveGeneric
  - DeriveDataTypeable
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
  - UndecidableInstances

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O2

executables:
  linter:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -optP-Wno-nonportable-include-path
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linter

tests:
  linter-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linter
      - hspec
      - text
      - bytestring
# # Define flags used by "yesod devel" to make compilation faster
# flags:
#   library-only:
#     description: Build for use with "yesod devel"
#     manual: false
#     default: false
#   dev:
#     description: Turn on development settings, like auto-reload templates.
#     manual: false
#     default: false
