name: argus
version: "1.0.0"
synopsis: Argus - The All-Seeing Haskell Static Analyzer
description: |
  Argus is a powerful Haskell linter that handles Template Haskell, detects unused code,
  enforces naming conventions, finds space leaks and security issues, and provides
  format-preserving auto-fixes. Named after the all-seeing giant of Greek mythology.
license: MIT
author: Quinten
maintainer: quinten@example.com
category: Development
github: quintenkasteel/argus

data-files:
  - data/default-rules.toml

dependencies:
  - base >= 4.17 && < 5

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedRecordDot
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-deriving-strategies
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wunused-packages
  - -fwrite-ide-info
  - -hiedir=.hie
  # Suppress macOS case-sensitivity warnings from clang CPP
  # See: https://github.com/commercialhaskell/stack/issues/3918
  - -optP-Wno-nonportable-include-path

library:
  source-dirs: src
  dependencies:
    # Text and data structures
    - text >= 2.0
    - bytestring >= 0.11
    - containers >= 0.6
    - hashable >= 1.4

    # GHC parsing (replaces haskell-src-exts)
    - ghc-lib-parser >= 9.6
    - ghc-lib-parser-ex >= 9.6

    # Configuration
    - tomland >= 1.3
    - yaml >= 0.11
    - aeson >= 2.1

    # CLI and output
    - optparse-applicative >= 0.18
    - prettyprinter >= 1.7
    - prettyprinter-ansi-terminal >= 1.1
    - ansi-terminal >= 0.11

    # File system
    - directory >= 1.3
    - filepath >= 1.4
    - process >= 1.6

    # Utilities
    - transformers >= 0.5
    - mtl >= 2.2
    - time >= 1.12
    - deepseq >= 1.4
    - Diff >= 0.4
    - temporary >= 1.3

    # Regex for pattern matching
    - regex-tdfa >= 1.3

    # Arrays for edit distance
    - array >= 0.5

    # SYB for generic traversals (AST matching)
    - syb >= 0.7

    # JSON output (for SARIF, etc.)
    - aeson-pretty >= 0.8

    # Concurrency for LSP server and parallel analysis
    - stm >= 2.5
    - async >= 2.2
    - parallel >= 3.2

    # HIE file analysis for semantic features
    - hiedb >= 0.6
    - ghc
    - sqlite-simple >= 0.4

    # Cryptographic hashing for baseline fingerprints
    - cryptonite >= 0.30

    # Networking for daemon mode
    - network >= 3.1
    - unix >= 2.7

    # Random for LSP progress tokens
    - random >= 1.2

    # Runtime Haskell evaluation for custom predicates
    - hint >= 0.9

    # Better parsing for expression language
    - megaparsec >= 9.0

    # File system watching for plugin hot-reload
    - fsnotify >= 0.4

    # UUID generation for transaction IDs
    - uuid >= 1.3

  exposed-modules:
    # Core types and utilities
    - Argus.Types
    - Argus.Utils
    - Argus.Config
    - Argus.Config.Validation

    # Internal utilities
    - Argus.Internal.DList

    # Analysis modules
    - Argus.Analysis.Comments
    - Argus.Analysis.Parallel
    - Argus.Analysis.ResourceLimits
    - Argus.Analysis.Syntactic
    - Argus.Analysis.Semantic
    - Argus.Analysis.DepGraph
    - Argus.Analysis.Unused
    - Argus.Analysis.Complexity
    - Argus.Analysis.Architecture
    - Argus.Analysis.ArchitectureDSL
    - Argus.Analysis.Cache
    - Argus.Analysis.TemplateHaskell
    - Argus.Analysis.Fingerprint
    - Argus.Analysis.Similarity
    - Argus.Analysis.Duplicate
    - Argus.Analysis.Incremental
    - Argus.Analysis.Metrics
    - Argus.Analysis.RuleTiming
    - Argus.Analysis.Purity
    - Argus.Analysis.ProfilingAggregation
    - Argus.Analysis.TextProcessing
    - Argus.Analysis.BenchGuided
    - Argus.Analysis.OrphanGraph
    - Argus.Analysis.Semver

    # Rule system
    - Argus.Rules.Types
    - Argus.Rules.Naming
    - Argus.Rules.Patterns
    - Argus.Rules.Imports
    - Argus.Rules.Parser
    - Argus.Rules.Partial
    - Argus.Rules.SpaceLeaks
    - Argus.Rules.Security
    - Argus.Rules.Performance
    - Argus.Rules.Pragmas
    - Argus.Rules.DSL
    - Argus.Rules.Redundant
    - Argus.Rules.Modernize
    - Argus.Rules.SmartImports
    - Argus.Rules.Extensions
    - Argus.Rules.ConfigurableRules
    - Argus.Rules.ASTMatch
    - Argus.Rules.Engine
    - Argus.Rules.SideConditions
    - Argus.Rules.Validation
    - Argus.Rules.Concurrency
    - Argus.Rules.ErrorHandling
    - Argus.Rules.Documentation
    - Argus.Rules.PerformanceValidated
    - Argus.Rules.Pack
    - Argus.Rules.SideConditions.Parser

    # Built-in lint rules
    - Argus.Rules.Builtin
    - Argus.Rules.Builtin.Safety
    - Argus.Rules.Builtin.Performance
    - Argus.Rules.Builtin.Security
    - Argus.Rules.Builtin.Style
    - Argus.Rules.Builtin.Correctness
    - Argus.Rules.Builtin.Brackets
    - Argus.Rules.Builtin.TypeAnnotations
    - Argus.Rules.Builtin.CodeSmells
    - Argus.Rules.Builtin.Lambda
    - Argus.Rules.Builtin.Monadic
    - Argus.Rules.Builtin.ListRecursion
    - Argus.Rules.Builtin.TypeclassLaws
    - Argus.Rules.Builtin.Foldable
    - Argus.Rules.Builtin.Numeric
    - Argus.Rules.Builtin.Strings
    - Argus.Rules.Builtin.Records
    - Argus.Rules.Builtin.Prelude
    - Argus.Rules.Builtin.IO
    - Argus.Rules.Builtin.Containers
    - Argus.Rules.Builtin.Transformers
    - Argus.Rules.Builtin.Testing
    - Argus.Rules.Builtin.FFI
    - Argus.Rules.Builtin.TypeFamilies
    - Argus.Rules.Builtin.GADTs
    - Argus.Rules.Builtin.Deriving
    - Argus.Rules.Builtin.Lenses
    - Argus.Rules.Builtin.Async
    - Argus.Rules.Builtin.List
    - Argus.Rules.Builtin.Maybe
    - Argus.Rules.Builtin.Either
    - Argus.Rules.Builtin.Boolean
    - Argus.Rules.Builtin.Comparison
    - Argus.Rules.Builtin.Tuple
    - Argus.Rules.Builtin.Composition
    - Argus.Rules.Builtin.Arrow
    - Argus.Rules.Builtin.Monoid
    - Argus.Rules.Builtin.Pattern
    - Argus.Rules.Builtin.Imports
    - Argus.Rules.Builtin.OWASP

    # Auto-fix modules
    - Argus.AutoFix.Types
    - Argus.AutoFix.Registry
    - Argus.AutoFix.Action
    - Argus.AutoFix.Pipeline
    - Argus.AutoFix.Config
    - Argus.AutoFix.Boolean
    - Argus.AutoFix.List
    - Argus.AutoFix.Monad
    - Argus.AutoFix.Partial
    - Argus.AutoFix.DSL
    - Argus.AutoFix.Template

    # Refactoring engine
    - Argus.Refactor.Engine
    - Argus.Refactor.ExactPrint
    - Argus.Refactor.Substitution
    - Argus.Refactor.SafeRefactor
    - Argus.Refactor.Validation
    - Argus.Refactor.FixGraph
    - Argus.Refactor.IncrementalValidation
    - Argus.Refactor.QualifyImport
    - Argus.Refactor.BatchFix
    - Argus.Refactor.SpanAdjustment
    - Argus.Refactor.SequentialFixer
    - Argus.Refactor.BangPattern
    - Argus.Refactor.DeclarationSort
    - Argus.Refactor.ConflictPreview

    # Output formatting
    - Argus.Output.Types
    - Argus.Output.Terminal
    - Argus.Output.Json
    - Argus.Output.Sarif
    - Argus.Output.Html
    - Argus.Output.JUnit
    - Argus.Output.CodeClimate
    - Argus.Output.Checkstyle
    - Argus.Output.Progress
    - Argus.Output.Enterprise
    - Argus.Output.Plain

    # Main orchestration
    - Argus.Core
    - Argus.CLI

    # Workspace (multi-project)
    - Argus.Workspace

    # CLI Submodules
    - Argus.CLI.Types
    - Argus.CLI.Common
    - Argus.CLI.Check
    - Argus.CLI.Fix
    - Argus.CLI.Unused
    - Argus.CLI.Init
    - Argus.CLI.Index
    - Argus.CLI.Watch
    - Argus.CLI.Diff
    - Argus.CLI.Baseline
    - Argus.CLI.Stats
    - Argus.CLI.Daemon
    - Argus.CLI.LSP
    - Argus.CLI.Architecture
    - Argus.CLI.Pack
    - Argus.CLI.Workspace
    - Argus.CLI.Rule

    # Documentation generation
    - Argus.Docs.Generator

    # GHC Plugin for TH support
    - Argus.Plugin

    # User Plugin System
    - Argus.Plugin.Types
    - Argus.Plugin.Registry

    # IDE Integration
    - Argus.IDE.Integration

    # LSP Server
    - Argus.LSP.Server
    - Argus.LSP.Completions
    - Argus.LSP.Diagnostics
    - Argus.LSP.Hover
    - Argus.LSP.Navigation
    - Argus.LSP.RuleInfo

    # Watch Mode
    - Argus.Watch

    # Suppression and baseline
    - Argus.Suppression
    - Argus.Baseline
    - Argus.Baseline.Types
    - Argus.Baseline.Diff
    - Argus.Baseline.IO

    # Daemon mode
    - Argus.Daemon

    # Import management (for auto-fix)
    - Argus.Imports.ImportDB
    - Argus.Imports.Manager
    - Argus.Imports.UsageAnalyzer
    - Argus.Imports.HIEAnalyzer
    - Argus.Imports.Pruner
    - Argus.Imports.Merger
    - Argus.Imports.AutoQualify

    # HIE-backed analysis (for type-safe auto-fix)
    - Argus.HIE.Types
    - Argus.HIE.Query
    - Argus.HIE.SymbolTable
    - Argus.HIE.TypeInfo
    - Argus.HIE.CrossModule
    - Argus.HIE.CrossVersion
    - Argus.HIE.FixValidator
    - Argus.HIE.IncrementalLoader
    - Argus.HIE.Incremental

    # Runtime Haskell evaluation
    - Argus.Runtime.Interpreter
    - Argus.Runtime.Sandbox
    - Argus.Runtime.Types

    # AST Pattern Language
    - Argus.Rules.ASTPatternParser
    - Argus.Rules.ASTPatternMatch

    # Expression Language
    - Argus.Rules.ExprLang
    - Argus.Rules.ExprLang.Parser
    - Argus.Rules.ExprLang.Types
    - Argus.Rules.ExprLang.Eval

    # Enhanced Plugin System
    - Argus.Plugin.HotReload
    - Argus.Plugin.Sandbox
    - Argus.Plugin.Manifest

    # Enhanced AutoFix
    - Argus.AutoFix.Semantic
    - Argus.AutoFix.MultiFile
    - Argus.AutoFix.Learning

    # Performance
    - Argus.Analysis.IncrementalCache
    - Argus.Analysis.ParallelRules

executables:
  argus:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - argus

tests:
  argus-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # Test-specific warning suppressions (tests have different conventions)
      - -Wno-incomplete-uni-patterns
      - -Wno-incomplete-patterns
      - -Wno-x-partial
      - -Wno-type-defaults
      - -Wno-unused-imports
      - -Wno-unused-top-binds
      - -Wno-unused-matches
      - -Wno-unused-local-binds
      - -Wno-name-shadowing
      - -Wno-orphans
    dependencies:
      - argus
      - hspec >= 2.11
      - QuickCheck >= 2.14
      - silently >= 1.2
      - containers >= 0.6
      - text >= 2.0
      - filepath >= 1.4
      - directory >= 1.3
      - bytestring >= 0.11
      - temporary >= 1.3
      - deepseq >= 1.4
      - stm >= 2.5
      - aeson >= 2.1
      - time >= 1.12
      - optparse-applicative >= 0.18
      - unix >= 2.7
      - tomland >= 1.3

benchmarks:
  argus-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - argus
      - criterion >= 1.6
      - deepseq
      - containers
      - text
