# Argus - Haskell Static Analyzer - Stack Configuration
# Using LTS 24.21 (GHC 9.10.3) - Latest stable as of November 2025
#
# Coverage: Run `stack test --coverage` or `make coverage` for HPC coverage.
# Note: Coverage requires a clean rebuild with coverage instrumentation.
#
# Quick commands:
#   stack build              - Build the project
#   stack test               - Run all tests
#   stack test --coverage    - Run tests with coverage (slow, requires rebuild)
#   stack bench              - Run benchmarks
#   stack run -- check src/  - Run argus on source

resolver: lts-24.21

packages:
  - .

extra-deps:
  # GHC parser as a library (latest for GHC 9.10)
  - ghc-lib-parser-9.10.3.20250912
  - ghc-lib-parser-ex-9.10.0.0

  # TOML configuration parsing
  - tomland-1.3.3.3
  - validation-selective-0.2.0.0

  # HIE file support for semantic analysis
  - hiedb-0.7.0.0
  - hie-compat-0.3.1.2

# GHC options for HIE file generation (needed for full analysis mode)
ghc-options:
  "$locals": -fwrite-ide-info -hiedir=.hie

# Allow newer versions of packages
allow-newer: true
